apiVersion: v1
kind: Service
metadata:
  labels:
    app: chopstick-classifier
  name: chopstick-classifier
spec:
  type: LoadBalancer # we need a load balancer to distribute our requests between all replicas in the Deployment
  ports:
  - port: 8500  # run this 
    name: grpc
  selector:
    app: chopstick-classifier # we are targeting pods labeled "app: chopstick classifier"
